### PR TITLE
Allow a Processing Strategy to be injected and configured via new startup extension methods

### LINKED ISSUE #83: Distribute cache concurrency issue
Hi @stefanprodan ,
When deploying a lots of api services(use distributed cache to store counter) behind load balance, every instance need to get conuter and use process' lock to increse count, as the code below
```
 using (await AsyncLock.WriterLockAsync(counterId).ConfigureAwait(false))
            {
                var entry = await _counterStore.GetAsync(counterId, cancellationToken);

                if (entry.HasValue)
                {
                    // entry has not expired
                    if (entry.Value.Timestamp + rule.PeriodTimespan.Value >= DateTime.UtcNow)
                    {
                        // increment request count
                        var totalCount = entry.Value.Count + _config.RateIncrementer?.Invoke() ?? 1;

                        // deep copy
                        counter = new RateLimitCounter
                        {
                            Timestamp = entry.Value.Timestamp,
                            Count = totalCount
                        };
                    }
                }

                // stores: id (string) - timestamp (datetime) - total_requests (long)
                await _counterStore.SetAsync(counterId, counter, rule.PeriodTimespan.Value, cancellationToken);
            }
```

I think it has concurrency issues, counter will not work correctly when a lots of requests come in. Every instance's counter count by themself then save to the cache store, the last one will cover the previous one.

Why not use Token Bucket algorithm to achieve this feature.

### PR DESCRIPTION
**Pull request by nick-cromwell**
Fixes #83 

This is a WIP and still needs supporting tests, but wanted to open this for discussion.

This takes after the work of @simonhaines in his [atomic-lua](https://github.com/statusas/AspNetCoreRateLimit/tree/atomic-lua) branch and adds a ProcessingStrategy for AsyncKeyLocker and also StackExchangeRedis allowing both to function while being mostly backwards compatible. The one exception is the need to register the IProcessingStrategyFactory with the ServiceProvider - which has been simplified with the new extension methods. The IProcessingStrategyFactory isn't perfect, but it avoids the need for more complicated injection strategies or container like Autofac.

This would require a major version bump.

### CODE REVIEW

**Comment by cristipufu** [comment]
Hi @nick-cromwell, great stuff. As this is such a major change, I would like to roll it out incrementally and split this PR into multiple PRs and maybe even multiple projects & NuGet packages (eg: AspNetCoreRateLimit.Redis - to avoid unwanted dependencies).

So I think that these should be the steps moving forward:
- Add the processing strategy refactoring PR
- (I was planning on replacing the AsyncLock with a ConcurrentDictionary for better perf https://github.com/SixLabors/ImageSharp.Web/pull/124)
- Major version bump
- Add a new project AspnetCoreRatelimit.Redis with the StackExchange.Redis lua script implementation
- Deploy the new project as a new NuGet package

Thanks for your contribution!

**Comment by nick-cromwell** [comment]
That sounds like a good plan, give me a few days I'll get those out.

**Comment by nick-cromwell** [comment]
@cristipufu Happy new year. This ready to be merged whenever you're available and I have tested the Redis Lua script processor in a separate branch. I'll open a PR for that once we've bumped the major version.

**Comment by simonhaines** [comment]
Injecting the processing strategy is a much cleaner approach than the one used in my fork, and fits the overall design of this library far better. I prefer this over my own work, and will update/redirect my fork when this is merged. Thank you @nick-cromwell for taking the time to integrate this, and to @cristipufu for the library in the first place!

**Comment by nick-cromwell** [comment]
@cristipufu Can we version bump and merge this in the near future. The concurrency issue is still receiving a fair amount of attention. #83

**Comment by cristipufu** [comment]
@nick-cromwell many thanks for your contribution! Feel free to add the `AspNetCoreRateLimit.Redis` extension project with a new PR and I'll publish it as a new NuGet package. 

I renamed the startup extensions & added a new one with a generic parameter to easily change the processing strategy.

Thanks!

cc: @stefanprodan can you please add @nick-cromwell as a contributor to this project?

**Comment by nick-cromwell** [comment]
Project was added in PR #210. Happy to help!

**Pull request merged**
