### PR TITLE
Support parameters in QuotaExceededMessage

### PR DESCRIPTION
**Pull request by emrahcetiner**
use limit and period values in QuotaExceededMessage

### CODE REVIEW

**Comment by OkanKaradag** [comment]
when to merge this commit?

**Comment by fucukur** [comment]
when is it merged @stefanprodan

**Comment by mrtaltnn** [comment]
Thanks @emrahcetiner. When is it merged @stefanprodan

**Comment by ozanince** [comment]
When will you merge this?

**Comment by sparksterz** [comment]
Because you guys seem a bit eager, you can always build a pre-release nuget package and add it to an internal package source while you wait for the merger and build of the next version. One of my requests merged back in January, but I used the included powershell script to build a pre-release for my needs and added it to an internal proget server. This would allow you to pull it in as a nuget still if you manage to have a server around to utilize or spin up.

**Comment by cristipufu** [comment]
There's a workaround to accomplish this (i needed to return a `json` response):

- Add custom middleware implementation:

```C#
public class IpRateLimitJsonMiddleware : IpRateLimitMiddleware
{
    private readonly IpRateLimitOptions _options;

    public IpRateLimitJsonMiddleware(RequestDelegate next,
            IOptions<IpRateLimitOptions> options,
            IRateLimitCounterStore counterStore,
            IIpPolicyStore policyStore,
            ILogger<IpRateLimitMiddleware> logger,
            IIpAddressParser ipParser = null
            ) : base(next, options, counterStore, policyStore, logger, ipParser)
    {
            _options = options.Value;
    }

    public override Task ReturnQuotaExceededResponse(HttpContext httpContext, RateLimitRule rule, string retryAfter)
    {
        var message = string.IsNullOrEmpty(_options.QuotaExceededMessage) ? $"API calls quota exceeded! maximum admitted {rule.Limit} per {rule.Period}." : _options.QuotaExceededMessage;

        var content = new
        {
                Message = message
        };

        if (!_options.DisableRateLimitHeaders)
        {
            httpContext.Response.Headers["Retry-After"] = retryAfter;
        }

        httpContext.Response.StatusCode = _options.HttpStatusCode;
        httpContext.Response.ContentType = "application/json";

        return httpContext.Response.WriteAsync(JsonConvert.SerializeObject(content));
    }
}
```

- Use your custom middleware instead of the predefined one:
```C#
//app.UseIpRateLimiting();
app.UseMiddleware<IpRateLimitJsonMiddleware>();
```

**Pull request merged**
